### ISSUE TITLE
Hello, is there another way to download, I can't get on Google, thank you very much!

### ISSUE THREAD

**Issue by kstudy123** [mmahdavian/STPOTR#2]

**Comment by mmahdavian** [comment]
Hi. Which file can't you download?

**Comment by kstudy123** [comment]
Hello, sorry I just saw your reply, thank you very much, the problem has been solved. But I have one more question: about your internal non-autoregressive model, I checked the potr but found that it is not explained in detail, may I ask if the input qkv of the internal decoder of the model is only summed with the position code, and how it achieves non-autoregressive? Thank you very much for your patient answer!

**Comment by mmahdavian** [comment]
Hello again. Sorry for delay in my reply. The model adds the encoder embeddings for trajectory with the output of multi-head attention module which is applied to encoder embeddings of pose and trajectory sections. Then it is used in another Multi-head attention module as q and k. The v would be the last hip position coppied m=20 times. The decoder actually tries to find the difference between that point and the next values in each frame. The model becomes non-autoregressive for that reason. We don't need to calculate each value one by one. The model tries to predict them all together at the same time.
