### ISSUE TITLE
visualize 

### ISSUE THREAD

**Issue by kstudy123** [mmahdavian/STPOTR#3]
Hello, thank you very much for sharing. How did you visualize the Fig. 3 in your paper? I read your "visualize" folder, and I want to use "forward_kinematics.py" for visualization, but the previous training did not save the h5py file, how did you draw the image? How did you draw the image? Thank you very much for your answer!

**Comment by mmahdavian** [comment]
Hi. If you check the model/testing.py code it has a a function for visualization. Go to the last two line and switch the functions.
