### ISSUE TITLE
operation about camera

### ISSUE THREAD

**Issue by Deante-dx** [mmahdavian/STPOTR#4]
Hi there,

I've come across various camera-related operations. I would like to understand the significance of these operations and how they relate to the overall data processing pipeline. Could someone kindly provide a detailed explanation of the camera operations and their relevance in data processing?

codes in [H36MDataset_v3](https://github.com/mmahdavian/STPOTR/blob/main/data/H36MDataset_v3.py)

Thank you in advance for your assistance and guidance!

Best regards,

**Comment by mmahdavian** [comment]
Hello. The lines of the code you were mentioning were for data augmentation. Currently the dataset contains the data for the mocap markers with respect to 4 cameras. We added some imaginary cameras and converted our data to their coordinate space. It helped in order to improve the model accuracy.

**Comment by Deante-dx** [comment]
> Hello. The lines of the code you were mentioning were for data augmentation. Currently the dataset contains the data for the mocap markers with respect to 4 cameras. We added some imaginary cameras and converted our data to their coordinate space. It helped in order to improve the model accuracy.

Thanks for your response. 
As shown in the code below, augment with respect to a random camera does not have a new entry_key to save it, so it will overwrite the previous data. Why is it done this way?
```python
`added_sact= 400
 for aug in range(len(self._augment_cameras_ang)):
       added_sact += 100
       ang = self._augment_cameras_ang[aug]
       x_cam = self._augment_cameras_x[aug]
       y_cam = self._augment_cameras_y[aug]
       ## augment with respect to a random camera
       new_seq, new_seq_traj = self.new_camera_data(s_id,correct_action,sact,added_sact,ang,x_cam,y_cam,action_sequence_main)
       self._data[entry_key] = new_seq
       self._traj[entry_key] = new_seq_traj`

**Comment by mmahdavian** [comment]
@Deante-dx Sorry for the late reply. It doesn't overwrite them. It adds them to the total settings by another line of the code.
